// src/components/Footer.tsx
import { HouseWifi } from "lucide-react";
import { useEffect, useState } from "react";

interface FooterProps {
  internalUrl: string;
}

function Footer({ internalUrl }: FooterProps) {
  const [isReachable, setIsReachable] = useState(false);

  useEffect(() => {
    const checkUrl = async () => {
      try {
        await fetch(internalUrl, {
          method: "HEAD",
          mode: "no-cors",
          signal: AbortSignal.timeout(3000) // 3 second timeout
        });
        setIsReachable(true);
      } catch {
        setIsReachable(false);
      }
    };

    if (internalUrl) {
      checkUrl();
    }
  }, [internalUrl]);

  return (
    <>
      <div className="flex justify-between p-4 text-xs font-normal">
        <div>
          {isReachable && (
            <a
              href={internalUrl}
              target="_blank"
              className="text-muted hover:text-primary transition-all duration-200 ease-in-out">
              <HouseWifi className="w-6 h-6" />
            </a>
          )}
        </div>
        <div>
          
        </div>
      </div>
    </>
  );
}

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
	import { HouseWifi } from '@lucide/svelte';

	let { internalUrl }: { internalUrl: string } = $props();

	let isReachable = $state(false);

	$effect(() => {
		if (!internalUrl) return;
		checkUrl();

		async function checkUrl() {
			try {
				await fetch(internalUrl, {
					method: 'HEAD',
					mode: 'no-cors',
					signal: AbortSignal.timeout(3000) // 3 second timeout
				});
				isReachable = true;
			} catch {
				isReachable = false;
			}
		}
	});
</script>

<div class="flex justify-between p-4 text-xs font-normal">
	<div>
		{#if isReachable}
			<a
				href={internalUrl}
				target="_blank"
				class="text-white/60 transition-all duration-200 ease-in-out hover:text-white dark:text-black/60 dark:hover:text-black"
			>
				<HouseWifi class="h-6 w-6" />
			</a>
		{/if}
	</div>
	<div></div>
</div>
